name: nodejs18

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - master
  schedule:
  - cron: '30 12 * * 3'

jobs:
  arm64:
    runs-on: arvato
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 1
    - name: Login to GitHub Packages Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push Latest
      uses: docker/build-push-action@v6
      with:
        push: true
        pull: true
        file: ./Dockerfile.nodejs18
        tags: ghcr.io/arvatoaws-labs/lambda-pipeline/nodejs18:latest-arm64
        cache-from: type=registry,ref=ghcr.io/arvatoaws-labs/lambda-pipeline/nodejs18:latest-arm64
        cache-to: type=inline
  amd64:
    runs-on: arvato-x86
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 1
    - name: Login to GitHub Packages Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and Push Latest
      uses: docker/build-push-action@v6
      with:
        push: true
        pull: true
        file: ./Dockerfile.nodejs18
        tags: ghcr.io/arvatoaws-labs/lambda-pipeline/nodejs18:latest-amd64
        cache-from: type=registry,ref=ghcr.io/arvatoaws-labs/lambda-pipeline/nodejs18:latest-amd64
        cache-to: type=inline
  manifest:
    runs-on: arvato
    needs: [arm64, amd64]
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 1
    - name: Login to GitHub Packages Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Merge manifests Latest
      run: |
        set -x
        echo "Merging manifests"
        docker manifest create "ghcr.io/arvatoaws-labs/lambda-pipeline/nodejs18:latest" "ghcr.io/arvatoaws-labs/lambda-pipeline/nodejs18:latest-arm64" "ghcr.io/arvatoaws-labs/lambda-pipeline/nodejs18:latest-amd64"
        docker manifest annotate --arch arm64 "ghcr.io/arvatoaws-labs/lambda-pipeline/nodejs18:latest" "ghcr.io/arvatoaws-labs/lambda-pipeline/nodejs18:latest-arm64"
        docker manifest annotate --arch amd64 "ghcr.io/arvatoaws-labs/lambda-pipeline/nodejs18:latest" "ghcr.io/arvatoaws-labs/lambda-pipeline/nodejs18:latest-amd64"
        docker manifest push "ghcr.io/arvatoaws-labs/lambda-pipeline/nodejs18:latest"
